### PR TITLE
change pgrep to fix issue for kube-apiserver

### PR DESCRIPTION
**Pull request by mitulshah-suse**
Related to https://github.com/rancher/rancher/issues/32935

### CODE REVIEW

**Review by prachidamle — COMMENTED** [review]
Can we run some tests based on this ticket https://github.com/rancher/rancher/issues/26598 to ensure we dont hit problems?

**Comment by mitulshah-suse** [comment]
> Can we run some tests based on this ticket [rancher/rancher#26598](https://github.com/rancher/rancher/issues/26598) to ensure we dont hit problems?

I created dummy processes on worker node with arguments --kube-apiserver. This was causing failures in existing setup.
The fix ensured that such arguments will not interfere with cis scans. 
The only scenario in which it will fail is if there are binaries named kube-apiserver running on the worker node, which normally would not be the case.

**Review by prachidamle — COMMENTED** [review]
ok, can we please verify CIS scan tests for all the cluster types rke1/rk2/k3s are passing with the change

**Comment by mitulshah-suse** [comment]
> ok, can we please verify CIS scan tests for all the cluster types rke1/rk2/k3s are passing with the change

yes, i verified for all rke1/rke2/k3s as part of the test..

**Review by prachidamle — DISMISSED** [review]

**Comment by mitulshah-suse** [comment]
For some reason the drone check is not getting triggered and the merging is blocked on that. I tried updating the PR again to trigger the check, but did not help.
@prachidamle Can you please advise? If you have permission, maybe you can merge it as well.

**Review by prachidamle — APPROVED** [review]

**Pull request merged**
