### PR TITLE
Fix K8s 1.24 cluster specific test failures on RKE1 and K3s hardened cluster

### PR DESCRIPTION
**Pull request by rayandas**
Related: https://github.com/rancher/cis-operator/issues/135
https://github.com/rancher/cis-operator/issues/153

After QA testing we found few failures as mentioned on the issue comments, this PR fixes them. Attaching the snapshots below
K3s-hardened CIS 1.6 and 1.20 fix:
k3s-hardened

RKE1-hardened 1.5 1.6 1.20 and 1.23 fix:
RKE1-hardened-mn

### CODE REVIEW

**Review by prachidamle — COMMENTED** [review]
Only one comment; rest looks good to me.

**Comment by prachidamle** [comment]
Going to add @macedogm for review, since I am going to be OOO for few days

**Comment by rayandas** [comment]
@prachidamle I ran the scans on a K8s v1.23 rke1 hardened cluster. All the tests are passing. but when running the tests on v1.24 rke1 hardened cluster `1.2.18`/`1.2.19`, `4.1.7`, `4.1.8` is failing. `1.2.18`/`1.2.19` are the failures which is expected because `--insecure-port` flag has been permanently removed from v1.24 (It was deprecated in 1.10). 
But the script for 4.1.7 and 4.1.8 check is failing only on 1.24 clusters. (and after this changes it's working for both K8s 1.23 and 1.24)
cc: @macedogm

**Review by macedogm — APPROVED** [review]

**Comment by macedogm** [comment]
I wasn't able to test all the scenarios, but overall LGTM.

**Pull request merged**
