### PR TITLE
Update to using upstream kube-bench since all fixes are merged upstream

### PR DESCRIPTION
**Pull request by prachidamle**
Update kube-bench to use upstream latest v0.6.8 release

### CODE REVIEW

**Comment by dhruvmewada15** [comment]
@prachidamle Was the CIS scan running successfully after updating the binary to `v0.6.8` ? Asking because I had tried updating it to `v0.6.6` some time back but there is a difference in the the result json file structure of `v0.2.3` and `v0.6.6` and summarizer was not able to read it.

**Comment by rayandas** [comment]
@prachidamle https://github.com/rancher/security-scan/pull/75 these changes will unblock us for current release. We've started working on to use upstream kube-bench (see [issue](https://github.com/rancher/cis-operator/issues/142)) but it needs some significant code changes (current Go version is 1.12).

**Comment by samkulkarni20** [comment]
@prachidamle What Dhruv & Rayan are trying to say is that we've tried the approach in this PR & it introduces many issues with all the scan profiles. Hence we've recreated Murali's fork for the time being. See PR #75 . We can use it to fix the build issues for the release blocker [security scan rke2 failures issue](https://github.com/rancher/rancher/issues/37397).

**Comment by macedogm** [comment]
I tried to run a CIS scan with this upstream kube-bench update and it failed.

image

**Review by macedogm — CHANGES_REQUESTED** [review]
I tried to run a CIS scan with this upstream kube-bench update and it failed.

image

**Comment by prachidamle** [comment]
@dhruvmewada15 @rayandas  Have we tried using upstream release `v0.6.4`? That release is immediately after the fixes done the earlier fork.

**Comment by prachidamle** [comment]
Closing in favor of https://github.com/rancher/security-scan/pull/75

**Pull request closed without merging**
