### PR TITLE
Add cis-1.20 profiles for k3s

### PR DESCRIPTION
**Pull request by dhruvmewada15**
This PR introduces upstream [cis-1.20](https://github.com/aquasecurity/kube-bench/tree/main/cfg/cis-1.20) benchmark profiles for the security scan for k3s cluster :

- k3s-cis-1.20-permissive
- k3s-cis-1.20-hardened

Linked Issue:
https://github.com/rancher/cis-operator/issues/135

### CODE REVIEW

**Comment by macedogm** [comment]
@anupama2501 We can use this profile for https://github.com/rancher/rancher/issues/37493.

**Comment by dhruvmewada15** [comment]
K3s single node non-hardened cluster:
image

K3s multi node non-hardened cluster:
_**Note**: CIS Scan is failing for this cluster type but so is the result of `k3s-cis-1.6-permissive` profile._
image

K3s multi node hardened cluster:
image

**Comment by dhruvmewada15** [comment]
@macedogm Can you please review this PR?

**Review by macedogm — APPROVED** [review]
LGTM

I tested both `K3s single node non-hardened cluster` and `K3s single node hardened cluster` and the scans passed as expected.

I haven't tested the `multi node` setup.

**Pull request merged**
