### PR TITLE
Add RKE2 Specific CIS Checks

### PR DESCRIPTION
**Pull request by briandowns**
This PR adds a number of scripts and CIS checks for the RKE2 binaries, and service file permissions and ownership.

PR resolves RKE2 issue 514 - https://github.com/rancher/rke2/issues/514

### CODE REVIEW

**Comment by cjellick** [comment]
Will this immediately show up in the next release of Rancher if it was merged?

**Comment by cjellick** [comment]
I wonder if we should move the tests into their own "section" like 6.x.x and i think if we do this, we also need to update docs and self-assessment guide to have these.

**Comment by cjellick** [comment]
I'll ask that we don't merge until we talk through when and how this would land WRT rancher.

**Comment by Kevin-De-Koninck** [comment]
What is the current state regarding this PR?

**Comment by andypitcher** [comment]
I believe this PR can be closed, the RKE2 profiles were made available, along with the concerned scripts:

```
$ ls security-scan/package/cfg/ | grep rke2
rke2-cis-1.20-hardened
rke2-cis-1.20-permissive
rke2-cis-1.23-hardened
rke2-cis-1.23-permissive
rke2-cis-1.24-hardened
rke2-cis-1.24-permissive
rke2-cis-1.5-hardened
rke2-cis-1.5-permissive
rke2-cis-1.6-hardened
rke2-cis-1.6-permissive
rke2-cis-1.7-hardened
rke2-cis-1.7-permissive
```

As for the ConfigMap `config.yaml` that should embed the binaries and paths for RKE2, an issue has been created to have one config.yaml per profile: [Customize variables paths and binaries for rke, rke2 and k3s in their own config.yaml](https://github.com/rancher/cis-operator/issues/211). 

@briandowns and @rayandas could you confirm this ?

**Pull request closed without merging**
