### PR TITLE
Change to BCI and bump to 15.4

### PR DESCRIPTION
**Pull request by superseb**
- Align with standardized BCI
- 15.3 is EOL

### CODE REVIEW

**Comment by superseb** [comment]
@rayandas please include this in the next RC

**Comment by rayandas** [comment]
@superseb sure will bump the tag when it'll be merged and add it in charts.

**Review by rayandas — APPROVED** [review]
LGTM

**Comment by rayandas** [comment]
@prachidamle Could you please review it once?

**Comment by rayandas** [comment]
After building the image I ran trivy scan on it and saw that there are multiple High and Medium CVEs. 
cc: @superseb

**Comment by superseb** [comment]
@rayandas Please share exact commands used to see if they are related to the base image.

**Comment by rayandas** [comment]
@superseb I built the image using `make` and then ran `trivy image rancher/security-scan:68b92ab-amd64` Seems like the base image doesn't have any CVEs but the current sonobuoy, kube-bench and kb-summarizer. Below is the output
Screenshot from 2023-02-08 21-10-39

**Comment by superseb** [comment]
OK, this PR is fine to go as we need to get rid of the EOL base image. The other CVEs should already be on the radar via https://github.com/rancherlabs/image-scanning/issues/2003.

**Comment by superseb** [comment]
@rayandas Are you waiting on @prachidamle @rancher/rancher2-helm-yes-dev ? Please review

**Review by prachidamle — APPROVED** [review]

**Comment by superseb** [comment]
@rayandas Please merge and tag a new RC to include this

**Comment by rayandas** [comment]
@superseb @prachidamle in what milestone should this change go if you can confirm before creating the tags and chart update PR.

**Comment by superseb** [comment]
From security, this needs to be in release asap as it moves from EOL image. Product wise is for @prachidamle or @Jono-SUSE-Rancher to decide I guess

**Comment by rayandas** [comment]
I’m asking this because we already past Bug complete for 2.7.2

**Comment by Jono-SUSE-Rancher** [comment]
I don't really have any details. It looks like it's already been merged. It can go in 2.7.2 if it's been merged already.

**Comment by rayandas** [comment]
Just FYI, the tag is not there yet. I was waiting for a confirmation. 
cc: @prachidamle

**Pull request merged**
