### PR TITLE
Add a E2E smoke test to confirm the scan works

### PR DESCRIPTION
**Pull request by pjbgf**
This PR creates a E2E smoke test which will:

- Create a kind cluster.
- Deploy the security-scan.
- Wait for the `Daemonset` to be created.
- Output the CIS Benchmark results (or errors during the process).
- Remove arch-specific commands, referring to the `ARCH` env var instead.

A timeout of 10 minutes has been set, in case the process gets stuck for some reason.

### CODE REVIEW

**Comment by rayandas** [comment]
@pjbgf could you please resolve the conflicts? Then we can reviewing it. 
cc: @andypitcher @JonCrowther

**Comment by pjbgf** [comment]
@rayandas we resolved the conflicts, PTAL.

**Comment by rayandas** [comment]
@JonCrowther Could you please review this?

**Review by JonCrowther — APPROVED** [review]
Tested myself and it works well. Thank you for adding this test

**Comment by JonCrowther** [comment]
Just as a heads up, this makes a similar change to this PR:
https://github.com/rancher/security-scan/pull/107

**Comment by pjbgf** [comment]
@JonCrowther nice shout, added that to the PR details.

**Comment by pjbgf** [comment]
Is there anything hold us back from merging this?

**Comment by pjbgf** [comment]
Relates to https://github.com/rancher/cis-operator/issues/151.

**Comment by pjbgf** [comment]
Relates to https://github.com/rancher/rancher/issues/40914.

**Pull request merged**
